export const Receivers = [
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasp1mf1-cig1',
    ipaddr: '172.28.138.46',
    recvaet: 'CIGA_MCF_ORDSTG',
    port: '6109',
    campus: 'MCF',
    sendaet1: 'ARCHIVE_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasp1mf1-cig2',
    ipaddr: '172.28.138.47',
    recvaet: 'CIGA_MCF_ORDSTG',
    port: '6109',
    campus: 'MCF',
    sendaet1: 'ARCHIVE_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'cigadmr01',
    ipaddr: '10.128.232.18',
    recvaet: 'CIGA_MCR_TST1',
    port: '6101',
    campus: 'MCR',
    sendaet1: 'ARCHIVE_SCU',
    sendaet2: 'TEAMTEST_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'cigadmr01',
    ipaddr: '10.128.232.18',
    recvaet: 'CIGA_MCR_TST2',
    port: '6102',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMTEST_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'cigadmr01',
    ipaddr: '10.128.232.18',
    recvaet: 'CIGA_MCR_TST3',
    port: '6103',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMTEST_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasp1mf2-cig1',
    ipaddr: '172.28.138.48',
    recvaet: 'CIGA_MCF_ORDSTG',
    port: '6109',
    campus: 'MCF',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasp1mf2-cig2',
    ipaddr: '172.28.138.49',
    recvaet: 'CIGA_MCF_ORDSTG',
    port: '6109',
    campus: 'MCF',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'cigadmr01',
    ipaddr: '10.128.232.18',
    recvaet: 'CIGA_MCR_TST4',
    port: '6104',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMTEST_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasp1ma1-cig1',
    ipaddr: '10.239.24.8',
    recvaet: 'CIGA_MCA_ORDSTG',
    port: '6109',
    campus: 'MCA',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasp1ma1-cig2',
    ipaddr: '10.239.24.9',
    recvaet: 'CIGA_MCA_ORDSTG',
    port: '6109',
    campus: 'MCA',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasp1ma2-cig1',
    ipaddr: '10.239.24.13',
    recvaet: 'CIGA_MCA_ORDSTG',
    port: '6109',
    campus: 'MCA',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasp1ma2-cig2',
    ipaddr: '10.239.24.17',
    recvaet: 'CIGA_MCA_ORDSTG',
    port: '6109',
    campus: 'MCA',
    sendaet1: 'ALI_SCU',
    sendaet2: 'TEAMTEST_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'cigadmr01',
    ipaddr: '10.128.232.18',
    recvaet: 'CIGA_MCR_NON_VIP',
    port: '7300',
    campus: 'MCR',
    sendaet1: '001SM1OT09DRSP',
    sendaet2: 'tstroke-cluster',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig1',
    ipaddr: '10.128.232.10',
    recvaet: 'CIGA_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'ARCHIVE_SCU',
    sendaet2: 'TEAMTEST_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig2',
    ipaddr: '10.128.232.83',
    recvaet: 'CIGA_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'ARCHIVE_SCU',
    sendaet2: 'TEAMTEST_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'cigadmr01',
    ipaddr: '10.128.232.18',
    recvaet: 'CIGA_MCR_TST5',
    port: '6105',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TESTDECO_SCP',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'R5085142',
    ipaddr: '172.24.110.194',
    recvaet: 'LQW_MCR_ORD',
    port: '6101',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'R5029423',
    ipaddr: '172.24.109.205',
    recvaet: 'LQ2_MCR_ORD_EV',
    port: '6200',
    campus: 'MCR',
    sendaet1: 'RST_ODM_TEST',
    sendaet2: 'RST_ODM_TEST',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'R5056003',
    ipaddr: '172.24.111.208',
    recvaet: 'DVP_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr2-cig1',
    ipaddr: '10.128.232.147',
    recvaet: 'CIGA_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'Compass',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr2-cig2',
    ipaddr: '10.128.232.148',
    recvaet: 'CIGA_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'Compass',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'R5085142',
    ipaddr: '172.24.110.194',
    recvaet: 'LQW_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'Compass',
    sendaet2: 'TEAMTEST_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'cigadmr01',
    ipaddr: '10.128.232.18',
    recvaet: 'CIGA_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'ARCHIVE_SCU',
    sendaet2: 'TEAMTEST_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'cigadmr01',
    ipaddr: '10.128.232.18',
    recvaet: 'CIGA_MCR_NON',
    port: '7100',
    campus: 'MCR',
    sendaet1: 'ARCHIVE_SCU',
    sendaet2: 'TEAMTEST_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'cigadmr01',
    ipaddr: '10.128.232.18',
    recvaet: 'CIGA_MCR_ORD_EV',
    port: '6200',
    campus: 'MCR',
    sendaet1: '001SM1OT09DRSP',
    sendaet2: 'US_CLUSTER_DT',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'cigadmr01',
    ipaddr: '10.128.232.18',
    recvaet: 'CIGA_MCR_ORD_PRE',
    port: '6110',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMTEST_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'cigadmr01',
    ipaddr: '10.128.232.18',
    recvaet: 'CIGA_MCR_NON_PRE',
    port: '7110',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMTEST_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'R5085152',
    ipaddr: '172.24.108.111',
    recvaet: 'WRYAN_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMTEST_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'R5085152',
    ipaddr: '172.24.108.111',
    recvaet: 'WRYAN_MCR_NON',
    port: '7100',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMTEST_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'R5085152',
    ipaddr: '172.24.108.111',
    recvaet: 'WRYAN_MCR_NONRAD',
    port: '5800',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMTEST_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'R5085152',
    ipaddr: '172.24.108.111',
    recvaet: 'WRYAN_MCR_FNLRAD',
    port: '5700',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMTEST_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'R5085142',
    ipaddr: '172.24.110.194',
    recvaet: 'LQW_MCR_NON',
    port: '7100',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMTEST_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasp2ei1-cig1',
    ipaddr: '10.128.200.17',
    recvaet: 'CIGA_MCR_ORDSTG',
    port: '6109',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasp2ei1-cig2',
    ipaddr: '10.128.200.20',
    recvaet: 'CIGA_MCR_ORDSTG',
    port: '6109',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasp2ha1-cig1',
    ipaddr: '10.128.200.8',
    recvaet: 'CIGA_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'cigadmr01',
    ipaddr: '10.128.232.18',
    recvaet: 'CIGA_MCR_TST6',
    port: '6106',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMTEST_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasp1ei1-cig1',
    ipaddr: '10.128.233.101',
    recvaet: 'CIGA_MCR_ORDSTG',
    port: '6109',
    campus: 'MCR',
    sendaet1: 'RST_ODM_TEST',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasp1ei1-cig2',
    ipaddr: '10.128.233.102',
    recvaet: 'CIGA_MCR_ORDSTG',
    port: '6109',
    campus: 'MCR',
    sendaet1: 'RST_ODM_TEST',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasp2ha1-cig1',
    ipaddr: '10.128.200.8',
    recvaet: 'CIGA_MCR_ORD_EV',
    port: '6200',
    campus: 'MCR',
    sendaet1: 'RST_ODM_TEST',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasp1fo1-cig1',
    ipaddr: '10.128.232.151',
    recvaet: 'CIGA_MCR_ORDSTG',
    port: '6109',
    campus: 'MCR',
    sendaet1: 'RST_ODM_TEST',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasp1fo1-cig2',
    ipaddr: '10.128.232.152',
    recvaet: 'CIGA_MCR_ORDSTG',
    port: '6109',
    campus: 'MCR',
    sendaet1: 'RST_ODM_TEST',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasp2ei1-cig2',
    ipaddr: '10.128.200.20',
    recvaet: 'CIGA_MCR_ORD_VIP',
    port: '6300',
    campus: 'MCR',
    sendaet1: 'RST_ODM_TEST',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasp2ha1-cig1',
    ipaddr: '10.128.200.8',
    recvaet: 'CIGA_MCR_ORDSTG',
    port: '6109',
    campus: 'MCR',
    sendaet1: 'RST_ODM_TEST',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasp2ha1-cig2',
    ipaddr: '10.128.200.14',
    recvaet: 'CIGA_MCR_ORDSTG',
    port: '6109',
    campus: 'MCR',
    sendaet1: 'RST_ODM_TEST',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'R5085142',
    ipaddr: '172.24.110.194',
    recvaet: 'LQW_MCR_ORD_EV',
    port: '6200',
    campus: 'MCR',
    sendaet1: 'RST_ODM_TEST',
    sendaet2: 'RST_ODM_TEST',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'R5085142',
    ipaddr: '172.24.110.194',
    recvaet: 'LQW_MCR_ORD_VIP',
    port: '6300',
    campus: 'MCR',
    sendaet1: 'RST_ODM_TEST',
    sendaet2: 'RST_ODM_TEST',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'cigadmr01',
    ipaddr: '10.128.232.18',
    recvaet: 'CIGA_MCR_ORD',
    port: '3401',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TESTDECO_SCP',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr2-cig1',
    ipaddr: '10.128.232.147',
    recvaet: 'CIGA_MCR_TST1',
    port: '6101',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr2-cig2',
    ipaddr: '10.128.232.148',
    recvaet: 'CIGA_MCR_TST2',
    port: '6102',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig1',
    ipaddr: '10.128.232.10',
    recvaet: 'CIGA_MCR_TST1',
    port: '6101',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig2',
    ipaddr: '10.128.232.83',
    recvaet: 'CIGA_MCR_TST2',
    port: '6102',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig1',
    ipaddr: '10.128.232.10',
    recvaet: 'CIGA_MCR_TST2',
    port: '6102',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig2',
    ipaddr: '10.128.232.83',
    recvaet: 'CIGA_MCR_TST1',
    port: '6101',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig1',
    ipaddr: '10.128.232.10',
    recvaet: 'CIGA_MCR_TST3',
    port: '6103',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig1',
    ipaddr: '10.128.232.10',
    recvaet: 'CIGA_MCR_TST4',
    port: '6104',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig2',
    ipaddr: '10.128.232.83',
    recvaet: 'CIGA_MCR_TST3',
    port: '6103',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig2',
    ipaddr: '10.128.232.83',
    recvaet: 'CIGA_MCR_TST4',
    port: '6104',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig1',
    ipaddr: '10.128.232.10',
    recvaet: 'CIGA_MCR_TST5',
    port: '6105',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig1',
    ipaddr: '10.128.232.10',
    recvaet: 'CIGA_MCR_TST6',
    port: '6106',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig2',
    ipaddr: '10.128.232.83',
    recvaet: 'CIGA_MCR_TST5',
    port: '6105',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig2',
    ipaddr: '10.128.232.83',
    recvaet: 'CIGA_MCR_TST6',
    port: '6106',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig1',
    ipaddr: '10.128.232.10',
    recvaet: 'CIGA_MCR_TST7',
    port: '6107',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig1',
    ipaddr: '10.128.232.10',
    recvaet: 'CIGA_MCR_TST8',
    port: '6108',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig2',
    ipaddr: '10.128.232.83',
    recvaet: 'CIGA_MCR_TST7',
    port: '6107',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig2',
    ipaddr: '10.128.232.83',
    recvaet: 'CIGA_MCR_TST8',
    port: '6108',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig1',
    ipaddr: '10.128.232.10',
    recvaet: 'CIGA_MCR_TST9',
    port: '6109',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig1',
    ipaddr: '10.128.232.10',
    recvaet: 'CIGA_MCR_TST11',
    port: '6111',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig2',
    ipaddr: '10.128.232.83',
    recvaet: 'CIGA_MCR_TST9',
    port: '6109',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig2',
    ipaddr: '10.128.232.83',
    recvaet: 'CIGA_MCR_TST11',
    port: '6111',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig1',
    ipaddr: '10.128.232.10',
    recvaet: 'CIGA_MCR_TST12',
    port: '6112',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig1',
    ipaddr: '10.128.232.10',
    recvaet: 'CIGA_MCR_TST13',
    port: '6113',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig2',
    ipaddr: '10.128.232.83',
    recvaet: 'CIGA_MCR_TST12',
    port: '6112',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig2',
    ipaddr: '10.128.232.83',
    recvaet: 'CIGA_MCR_TST13',
    port: '6113',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig1',
    ipaddr: '10.128.232.10',
    recvaet: 'CIGA_MCR_TST14',
    port: '6114',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig1',
    ipaddr: '10.128.232.10',
    recvaet: 'CIGA_MCR_TST15',
    port: '6115',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig2',
    ipaddr: '10.128.232.83',
    recvaet: 'CIGA_MCR_TST14',
    port: '6114',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig2',
    ipaddr: '10.128.232.83',
    recvaet: 'CIGA_MCR_TST15',
    port: '6115',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig1',
    ipaddr: '10.128.232.10',
    recvaet: 'CIGA_MCR_TST16',
    port: '6116',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig1',
    ipaddr: '10.128.232.10',
    recvaet: 'CIGA_MCR_TST17',
    port: '6117',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig2',
    ipaddr: '10.128.232.83',
    recvaet: 'CIGA_MCR_TST16',
    port: '6116',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig2',
    ipaddr: '10.128.232.83',
    recvaet: 'CIGA_MCR_TST17',
    port: '6117',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig1',
    ipaddr: '10.128.232.10',
    recvaet: 'CIGA_MCR_TST10',
    port: '6110',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'iasq1mr1-cig2',
    ipaddr: '10.128.232.83',
    recvaet: 'CIGA_MCR_TST10',
    port: '6110',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'R5192965',
    ipaddr: '10.205.11.13',
    recvaet: 'SLK_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'Compass',
    sendaet2: 'Compass',
  },
  {
    queue: 'test',
    aettype: 'receiver',
    hostname: 'R5193050',
    ipaddr: '172.24.110.220',
    recvaet: 'SLK_MCR_ORD',
    port: '6200',
    campus: 'MCR',
    sendaet1: 'Compass',
    sendaet2: 'Compass',
  },

  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'R5056003',
    ipaddr: '172.24.111.208',
    recvaet: 'DVP_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'ROEVIS901A',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mr2-cig1',
    ipaddr: '10.128.232.147',
    recvaet: 'CIGA_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'CLINICAL_SCP',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mr2-cig2',
    ipaddr: '10.128.232.148',
    recvaet: 'CIGA_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'CLINICAL_SCP',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mr2-cig1',
    ipaddr: '10.128.232.147',
    recvaet: 'CIGA_MCR_NON',
    port: '7100',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mr2-cig2',
    ipaddr: '10.128.232.148',
    recvaet: 'CIGA_MCR_NON',
    port: '7100',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'R5029423',
    ipaddr: '172.24.109.205',
    recvaet: 'LQW_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'Compass',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'R5029423',
    ipaddr: '172.24.109.205',
    recvaet: 'LQW_MCR_NON',
    port: '7100',
    campus: 'MCR',
    sendaet1: 'CLINICAL_SCP',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mr2-cig1',
    ipaddr: '10.128.232.147',
    recvaet: 'CIGA_MCR_ORD_EV',
    port: '6200',
    campus: 'MCR',
    sendaet1: 'Compass',
    sendaet2: 'UARCH_INT',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mr2-cig2',
    ipaddr: '10.128.232.148',
    recvaet: 'CIGA_MCR_ORD_EV',
    port: '6200',
    campus: 'MCR',
    sendaet1: 'Compass',
    sendaet2: 'UARCH_INT',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mr2-cig1',
    ipaddr: '10.128.232.147',
    recvaet: 'CIGA_MCR_ORD_VIP',
    port: '6300',
    campus: 'MCR',
    sendaet1: 'Compass',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mr2-cig2',
    ipaddr: '10.128.232.148',
    recvaet: 'CIGA_MCR_ORD_VIP',
    port: '6300',
    campus: 'MCR',
    sendaet1: 'Compass',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mr2-cig1',
    ipaddr: '10.128.232.147',
    recvaet: 'CIGA_MCR_NON_EV',
    port: '7200',
    campus: 'MCR',
    sendaet1: 'Compass',
    sendaet2: 'UARCH_INT',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mr2-cig2',
    ipaddr: '10.128.232.148',
    recvaet: 'CIGA_MCR_NON_EV',
    port: '7200',
    campus: 'MCR',
    sendaet1: 'Compass',
    sendaet2: 'UARCH_INT',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mr2-cig1',
    ipaddr: '10.128.232.147',
    recvaet: 'CIGA_MCR_NON_VIP',
    port: '7300',
    campus: 'MCR',
    sendaet1: '',
    sendaet2: '',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mr2-cig2',
    ipaddr: '10.128.232.148',
    recvaet: 'CIGA_MCR_NON_VIP',
    port: '7300',
    campus: 'MCR',
    sendaet1: 'FON_IMSU',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'R5029423',
    ipaddr: '172.24.109.205',
    recvaet: 'LQW_MCR_ORD_EV',
    port: '6200',
    campus: 'MCR',
    sendaet1: 'Compass',
    sendaet2: 'UARCH_INT',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'R5029423',
    ipaddr: '172.24.109.205',
    recvaet: 'LQW_MCR_NON_EV',
    port: '7200',
    campus: 'MCR',
    sendaet1: 'Compass',
    sendaet2: 'UARCH_INT',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'R5038087',
    ipaddr: '172.24.110.242',
    recvaet: 'BEN_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'R5038087',
    ipaddr: '172.24.110.242',
    recvaet: 'BEN_MCR_NON',
    port: '7100',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'R5085152',
    ipaddr: '172.24.108.111',
    recvaet: 'BYW_MCR_NON',
    port: '7100',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'R5085152',
    ipaddr: '172.24.108.111',
    recvaet: 'BYW_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1ma1-cig1',
    ipaddr: '10.239.24.22',
    recvaet: 'CIGA_MCA_ORD',
    port: '6100',
    campus: 'MCA',
    sendaet1: 'ARZMIDIATEST',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1ma1-cig2',
    ipaddr: '10.239.24.56',
    recvaet: 'CIGA_MCA_ORD',
    port: '6100',
    campus: 'MCA',
    sendaet1: 'ARZMIDIATEST',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1ma1-cig1',
    ipaddr: '10.239.24.22',
    recvaet: 'CIGA_MCA_ORD_EV',
    port: '6200',
    campus: 'MCA',
    sendaet1: 'ARZMIDIATEST',
    sendaet2: 'scimgarz-cluster',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1ma1-cig2',
    ipaddr: '10.239.24.56',
    recvaet: 'CIGA_MCA_ORD_EV',
    port: '6200',
    campus: 'MCA',
    sendaet1: 'ARZMIDIATEST',
    sendaet2: 'scimgarz-cluster',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1ma1-cig1',
    ipaddr: '10.239.24.22',
    recvaet: 'CIGA_MCA_ORD_VIP',
    port: '6300',
    campus: 'MCA',
    sendaet1: 'ARZMIDIATEST',
    sendaet2: 'scimgarz-cluster',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1ma1-cig1',
    ipaddr: '10.239.24.22',
    recvaet: 'CIGA_MCA_NON',
    port: '7100',
    campus: 'MCA',
    sendaet1: 'ARZMIDIATEST',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1ma1-cig2',
    ipaddr: '10.239.24.56',
    recvaet: 'CIGA_MCA_NON',
    port: '7100',
    campus: 'MCA',
    sendaet1: 'ARZMIDIATEST',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1ma1-cig1',
    ipaddr: '10.239.24.22',
    recvaet: 'CIGA_MCA_NON_EV',
    port: '7200',
    campus: 'MCA',
    sendaet1: 'ARZMIDIATEST',
    sendaet2: 'ARZMIDIATEST',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1ma1-cig2',
    ipaddr: '10.239.24.56',
    recvaet: 'CIGA_MCA_NON_EV',
    port: '7200',
    campus: 'MCA',
    sendaet1: 'ARZMIDIATEST',
    sendaet2: 'ARZMIDIATEST',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1ma1-cig1',
    ipaddr: '10.239.24.22',
    recvaet: 'CIGA_MCA_NON_VIP',
    port: '7300',
    campus: 'MCA',
    sendaet1: 'ARZMIDIATEST',
    sendaet2: 'ARZMIDIATEST',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mf1-cig1',
    ipaddr: '172.28.138.9',
    recvaet: 'CIGA_MCF_ORD',
    port: '6100',
    campus: 'MCF',
    sendaet1: 'ROEDCM902A',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mf1-cig2',
    ipaddr: '172.28.138.15',
    recvaet: 'CIGA_MCF_ORD',
    port: '6100',
    campus: 'MCF',
    sendaet1: 'ROEDCM902A',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mf1-cig1',
    ipaddr: '172.28.138.9',
    recvaet: 'CIGA_MCF_ORD_EV',
    port: '6200',
    campus: 'MCF',
    sendaet1: 'JAEVIS901A',
    sendaet2: 'scimgfla-cluster',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mf1-cig2',
    ipaddr: '172.28.138.15',
    recvaet: 'CIGA_MCF_ORD_EV',
    port: '6200',
    campus: 'MCF',
    sendaet1: 'JAEVIS901A',
    sendaet2: 'scimgfla-cluster',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mf1-cig1',
    ipaddr: '172.28.138.9',
    recvaet: 'CIGA_MCF_ORD_VIP',
    port: '6300',
    campus: 'MCF',
    sendaet1: 'JAEVIS901A',
    sendaet2: 'scimgfla-cluster',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mf1-cig1',
    ipaddr: '172.28.138.9',
    recvaet: 'CIGA_MCF_NON',
    port: '7100',
    campus: 'MCF',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mf1-cig2',
    ipaddr: '172.28.138.15',
    recvaet: 'CIGA_MCF_NON',
    port: '7100',
    campus: 'MCF',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mf1-cig1',
    ipaddr: '172.28.138.9',
    recvaet: 'CIGA_MCF_NON_EV',
    port: '7200',
    campus: 'MCF',
    sendaet1: 'JAEVIS901A',
    sendaet2: 'JAEVIS902A',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mf1-cig2',
    ipaddr: '172.28.138.15',
    recvaet: 'CIGA_MCF_NON_EV',
    port: '7200',
    campus: 'MCF',
    sendaet1: 'JAEVIS901A',
    sendaet2: 'JAEVIS902A',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mf1-cig1',
    ipaddr: '172.28.138.9',
    recvaet: 'CIGA_MCF_NON_VIP',
    port: '7300',
    campus: 'MCF',
    sendaet1: 'JAEVIS901A',
    sendaet2: 'JAEVIS902A',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1mf1-cig2',
    ipaddr: '172.28.138.15',
    recvaet: 'CIGA_MCF_ORD_VIP',
    port: '6300',
    campus: 'MCF',
    sendaet1: 'scimgfla-cluster',
    sendaet2: 'scimgfla-cluster',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'iasq1ma1-cig2',
    ipaddr: '10.239.24.56',
    recvaet: 'CIGA_MCA_ORD_VIP',
    port: '6300',
    campus: 'MCA',
    sendaet1: 'scimgarz-cluster',
    sendaet2: 'scimgarz-cluster',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'R5192965',
    ipaddr: '10.205.11.13',
    recvaet: 'SLK_MCR_ORD',
    port: '6200',
    campus: 'MCR',
    sendaet1: 'Compass',
    sendaet2: 'Compass',
  },
  {
    queue: 'int',
    aettype: 'receiver',
    hostname: 'R5193050',
    ipaddr: '172.24.110.220',
    recvaet: 'SLK_MCR_ORD',
    port: '6200',
    campus: 'MCR',
    sendaet1: 'Compass',
    sendaet2: 'Compass',
  },
  {
    queue: 'preintg',
    aettype: 'receiver',
    hostname: 'iasq1mr2-cig1',
    ipaddr: '10.128.232.147',
    recvaet: 'CIGA_MCR_ORDSTG',
    port: '6109',
    campus: 'MCR',
    sendaet1: 'CLINICAL_SCP',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'preintg',
    aettype: 'receiver',
    hostname: 'iasq1mr2-cig2',
    ipaddr: '10.128.232.148',
    recvaet: 'CIGA_MCR_ORDSTG',
    port: '6109',
    campus: 'MCR',
    sendaet1: 'CLINICAL_SCP',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'preintg',
    aettype: 'receiver',
    hostname: 'iasq1mr2-cig1',
    ipaddr: '10.128.232.147',
    recvaet: 'CIGA_MCR_NONSTG',
    port: '7109',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'preintg',
    aettype: 'receiver',
    hostname: 'iasq1mr2-cig2',
    ipaddr: '10.128.232.148',
    recvaet: 'CIGA_MCR_NONSTG',
    port: '7109',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'preintg',
    aettype: 'receiver',
    hostname: 'iasq1ma1-cig1',
    ipaddr: '10.239.24.22',
    recvaet: 'CIGA_MCA_ORDSTG',
    port: '6109',
    campus: 'MCA',
    sendaet1: 'ARZMIDIATEST',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'preintg',
    aettype: 'receiver',
    hostname: 'iasq1ma1-cig2',
    ipaddr: '10.239.24.56',
    recvaet: 'CIGA_MCA_ORDSTG',
    port: '6109',
    campus: 'MCA',
    sendaet1: 'ARZMIDIATEST',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'preintg',
    aettype: 'receiver',
    hostname: 'iasq1ma1-cig1',
    ipaddr: '10.239.24.22',
    recvaet: 'CIGA_MCA_NONSTG',
    port: '7109',
    campus: 'MCA',
    sendaet1: 'ARZMIDIATEST',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'preintg',
    aettype: 'receiver',
    hostname: 'iasq1ma1-cig2',
    ipaddr: '10.239.24.56',
    recvaet: 'CIGA_MCA_NONSTG',
    port: '7109',
    campus: 'MCA',
    sendaet1: 'ARZMIDIATEST',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'preintg',
    aettype: 'receiver',
    hostname: 'iasq1mf1-cig1',
    ipaddr: '172.28.138.9',
    recvaet: 'CIGA_MCF_ORDSTG',
    port: '6109',
    campus: 'MCF',
    sendaet1: 'ROEDCM902A',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'preintg',
    aettype: 'receiver',
    hostname: 'iasq1mf1-cig2',
    ipaddr: '172.28.138.15',
    recvaet: 'CIGA_MCF_ORDSTG',
    port: '6109',
    campus: 'MCF',
    sendaet1: 'ROEDCM902A',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'preintg',
    aettype: 'receiver',
    hostname: 'iasq1mf1-cig1',
    ipaddr: '172.28.138.9',
    recvaet: 'CIGA_MCF_NONSTG',
    port: '7109',
    campus: 'MCF',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMINT_SCP',
  },
  {
    queue: 'preintg',
    aettype: 'receiver',
    hostname: 'iasq1mf1-cig2',
    ipaddr: '172.28.138.15',
    recvaet: 'CIGA_MCF_NONSTG',
    port: '7109',
    campus: 'MCF',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAMINT_SCP',
  },

  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ei1-cig1',
    ipaddr: '10.128.233.101',
    recvaet: 'CIGA_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'CLINICAL_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ei1-cig2',
    ipaddr: '10.128.233.102',
    recvaet: 'CIGA_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'CLINICAL_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1fo1-cig1',
    ipaddr: '10.128.232.151',
    recvaet: 'CIGA_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'CLINICAL_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1fo1-cig2',
    ipaddr: '10.128.232.152',
    recvaet: 'CIGA_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'CLINICAL_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ei1-cig1',
    ipaddr: '10.128.233.101',
    recvaet: 'CIGA_MCR_NON',
    port: '7100',
    campus: 'MCR',
    sendaet1: 'CLINICAL_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ei1-cig2',
    ipaddr: '10.128.233.102',
    recvaet: 'CIGA_MCR_NON',
    port: '7100',
    campus: 'MCR',
    sendaet1: 'CLINICAL_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1fo1-cig1',
    ipaddr: '10.128.232.151',
    recvaet: 'CIGA_MCR_NON',
    port: '7100',
    campus: 'MCR',
    sendaet1: 'CLINICAL_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1fo1-cig2',
    ipaddr: '10.128.232.152',
    recvaet: 'CIGA_MCR_NON',
    port: '7100',
    campus: 'MCR',
    sendaet1: 'CLINICAL_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf1-cig1',
    ipaddr: '172.28.138.46',
    recvaet: 'CIGA_MCF_ORD',
    port: '6100',
    campus: 'MCF',
    sendaet1: 'FLA_ODM_PROD',
    sendaet2: 'ROEDCM008A',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf1-cig2',
    ipaddr: '172.28.138.47',
    recvaet: 'CIGA_MCF_ORD',
    port: '6100',
    campus: 'MCF',
    sendaet1: 'FLA_ODM_PROD',
    sendaet2: 'ROEDCM008A',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf2-cig1',
    ipaddr: '172.28.138.48',
    recvaet: 'CIGA_MCF_ORD',
    port: '6100',
    campus: 'MCF',
    sendaet1: 'FLA_ODM_PROD',
    sendaet2: 'ROEDCM008A',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf2-cig2',
    ipaddr: '172.28.138.49',
    recvaet: 'CIGA_MCF_ORD',
    port: '6100',
    campus: 'MCF',
    sendaet1: 'FLA_ODM_PROD',
    sendaet2: 'ROEDCM008A',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf1-cig1',
    ipaddr: '172.28.138.46',
    recvaet: 'CIGA_MCF_NON',
    port: '7100',
    campus: 'MCF',
    sendaet1: 'MCFMIDPROD1',
    sendaet2: 'MCFMIDPROD1',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf1-cig2',
    ipaddr: '172.28.138.47',
    recvaet: 'CIGA_MCF_NON',
    port: '7100',
    campus: 'MCF',
    sendaet1: 'MCFMIDPROD1',
    sendaet2: 'MCFMIDPROD1',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf2-cig1',
    ipaddr: '172.28.138.48',
    recvaet: 'CIGA_MCF_NON',
    port: '7100',
    campus: 'MCF',
    sendaet1: 'MCFMIDPROD1',
    sendaet2: 'MCFMIDPROD1',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf2-cig2',
    ipaddr: '172.28.138.49',
    recvaet: 'CIGA_MCF_NON',
    port: '7100',
    campus: 'MCF',
    sendaet1: 'MCFMIDPROD1',
    sendaet2: 'MCFMIDPROD1',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma1-cig1',
    ipaddr: '10.239.24.8',
    recvaet: 'CIGA_MCA_ORD',
    port: '6100',
    campus: 'MCA',
    sendaet1: 'ARZ_ODM_PROD',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma1-cig2',
    ipaddr: '10.239.24.9',
    recvaet: 'CIGA_MCA_ORD',
    port: '6100',
    campus: 'MCA',
    sendaet1: 'ARZ_ODM_PROD',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma2-cig1',
    ipaddr: '10.239.24.13',
    recvaet: 'CIGA_MCA_ORD',
    port: '6100',
    campus: 'MCA',
    sendaet1: 'ARZ_ODM_PROD',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma2-cig2',
    ipaddr: '10.239.24.17',
    recvaet: 'CIGA_MCA_ORD',
    port: '6100',
    campus: 'MCA',
    sendaet1: 'ARZ_ODM_PROD',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma1-cig1',
    ipaddr: '10.239.24.8',
    recvaet: 'CIGA_MCA_NON',
    port: '7100',
    campus: 'MCA',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma1-cig2',
    ipaddr: '10.239.24.9',
    recvaet: 'CIGA_MCA_NON',
    port: '7100',
    campus: 'MCA',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma2-cig1',
    ipaddr: '10.239.24.13',
    recvaet: 'CIGA_MCA_NON',
    port: '7100',
    campus: 'MCA',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma2-cig2',
    ipaddr: '10.239.24.17',
    recvaet: 'CIGA_MCA_NON',
    port: '7100',
    campus: 'MCA',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf1-cig1',
    ipaddr: '172.28.138.46',
    recvaet: 'CIGA_MCF_NON_VIP',
    port: '7300',
    campus: 'MCF',
    sendaet1: 'scimgfla-cluster',
    sendaet2: 'scimgfla-cluster',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf2-cig1',
    ipaddr: '172.28.138.48',
    recvaet: 'CIGA_MCF_NON_VIP',
    port: '7300',
    campus: 'MCF',
    sendaet1: 'scimgfla-cluster',
    sendaet2: 'scimgfla-cluster',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf1-cig1',
    ipaddr: '172.28.138.46',
    recvaet: 'CIGA_MCF_ORD_VIP',
    port: '6300',
    campus: 'MCF',
    sendaet1: '001SM1IIP12',
    sendaet2: 'URO5112_STSCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf2-cig1',
    ipaddr: '172.28.138.48',
    recvaet: 'CIGA_MCF_ORD_VIP',
    port: '6300',
    campus: 'MCF',
    sendaet1: '001SM1IIP12',
    sendaet2: 'URO5112_STSCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf1-cig1',
    ipaddr: '172.28.138.46',
    recvaet: 'CIGA_MCF_ORD_EV',
    port: '6200',
    campus: 'MCF',
    sendaet1: 'FLA_ODM_PROD',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf1-cig2',
    ipaddr: '172.28.138.47',
    recvaet: 'CIGA_MCF_ORD_EV',
    port: '6200',
    campus: 'MCF',
    sendaet1: 'FLA_ODM_PROD',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf2-cig1',
    ipaddr: '172.28.138.48',
    recvaet: 'CIGA_MCF_ORD_EV',
    port: '6200',
    campus: 'MCF',
    sendaet1: 'FLA_ODM_PROD',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf2-cig2',
    ipaddr: '172.28.138.49',
    recvaet: 'CIGA_MCF_ORD_EV',
    port: '6200',
    campus: 'MCF',
    sendaet1: 'FLA_ODM_PROD',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma1-cig1',
    ipaddr: '10.239.24.8',
    recvaet: 'CIGA_MCA_NON_VIP',
    port: '7300',
    campus: 'MCA',
    sendaet1: 'scimgarz-cluster',
    sendaet2: 'scimgarz-cluster',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma2-cig1',
    ipaddr: '10.239.24.13',
    recvaet: 'CIGA_MCA_NON_VIP',
    port: '7300',
    campus: 'MCA',
    sendaet1: 'scimgarz-cluster',
    sendaet2: 'scimgarz-cluster',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma1-cig1',
    ipaddr: '10.239.24.8',
    recvaet: 'CIGA_MCA_ORD_VIP',
    port: '6300',
    campus: 'MCA',
    sendaet1: 'A033913',
    sendaet2: 'scimgarz-cluster',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma2-cig1',
    ipaddr: '10.239.24.13',
    recvaet: 'CIGA_MCA_ORD_VIP',
    port: '6300',
    campus: 'MCA',
    sendaet1: 'A033913',
    sendaet2: 'scimgarz-cluster',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma1-cig1',
    ipaddr: '10.239.24.8',
    recvaet: 'CIGA_MCA_ORD_EV',
    port: '6200',
    campus: 'MCA',
    sendaet1: 'ARZ_ODM_PROD',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma1-cig2',
    ipaddr: '10.239.24.9',
    recvaet: 'CIGA_MCA_ORD_EV',
    port: '6200',
    campus: 'MCA',
    sendaet1: 'ARZ_ODM_PROD',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma2-cig1',
    ipaddr: '10.239.24.13',
    recvaet: 'CIGA_MCA_ORD_EV',
    port: '6200',
    campus: 'MCA',
    sendaet1: 'ARZ_ODM_PROD',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma2-cig2',
    ipaddr: '10.239.24.17',
    recvaet: 'CIGA_MCA_ORD_EV',
    port: '6200',
    campus: 'MCA',
    sendaet1: 'ARZ_ODM_PROD',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ei1-cig1',
    ipaddr: '10.128.233.101',
    recvaet: 'CIGA_MCR_NON_VIP',
    port: '7300',
    campus: 'MCR',
    sendaet1: 'scimage-cluster',
    sendaet2: 'tstroke-cluster',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1fo1-cig1',
    ipaddr: '10.128.232.151',
    recvaet: 'CIGA_MCR_NON_VIP',
    port: '7300',
    campus: 'MCR',
    sendaet1: 'scimage-cluster',
    sendaet2: 'tstroke-cluster',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ei1-cig1',
    ipaddr: '10.128.233.101',
    recvaet: 'CIGA_MCR_ORD_VIP',
    port: '6300',
    campus: 'MCR',
    sendaet1: '001SMRD140DRSP',
    sendaet2: 'W4X1',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1fo1-cig1',
    ipaddr: '10.128.232.151',
    recvaet: 'CIGA_MCR_ORD_VIP',
    port: '6300',
    campus: 'MCR',
    sendaet1: '001SMRD140DRSP',
    sendaet2: 'W4X1',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ei1-cig1',
    ipaddr: '10.128.233.101',
    recvaet: 'CIGA_MCR_ORD_EV',
    port: '6200',
    campus: 'MCR',
    sendaet1: 'IAU_CLUSTER',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ei1-cig2',
    ipaddr: '10.128.233.102',
    recvaet: 'CIGA_MCR_ORD_EV',
    port: '6200',
    campus: 'MCR',
    sendaet1: 'IAU_CLUSTER',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1fo1-cig1',
    ipaddr: '10.128.232.151',
    recvaet: 'CIGA_MCR_ORD_EV',
    port: '6200',
    campus: 'MCR',
    sendaet1: 'IAU_CLUSTER',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1fo1-cig2',
    ipaddr: '10.128.232.152',
    recvaet: 'CIGA_MCR_ORD_EV',
    port: '6200',
    campus: 'MCR',
    sendaet1: 'IAU_CLUSTER',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ei1-cig1',
    ipaddr: '10.128.233.101',
    recvaet: 'CIGA_MCR_NON_EV',
    port: '7200',
    campus: 'MCR',
    sendaet1: 'ALI_SCU',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ei1-cig2',
    ipaddr: '10.128.233.102',
    recvaet: 'CIGA_MCR_NON_EV',
    port: '7200',
    campus: 'MCR',
    sendaet1: 'ALI_SCU',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1fo1-cig1',
    ipaddr: '10.128.232.151',
    recvaet: 'CIGA_MCR_NON_EV',
    port: '7200',
    campus: 'MCR',
    sendaet1: 'ALI_SCU',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1fo1-cig2',
    ipaddr: '10.128.232.152',
    recvaet: 'CIGA_MCR_NON_EV',
    port: '7200',
    campus: 'MCR',
    sendaet1: 'ALI_SCU',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf1-cig1',
    ipaddr: '172.28.138.46',
    recvaet: 'CIGA_MCF_NON_EV',
    port: '7200',
    campus: 'MCF',
    sendaet1: 'ULTRA_ARCHIVE',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf1-cig2',
    ipaddr: '172.28.138.47',
    recvaet: 'CIGA_MCF_NON_EV',
    port: '7200',
    campus: 'MCF',
    sendaet1: 'ULTRA_ARCHIVE',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf2-cig1',
    ipaddr: '172.28.138.48',
    recvaet: 'CIGA_MCF_NON_EV',
    port: '7200',
    campus: 'MCF',
    sendaet1: 'ULTRA_ARCHIVE',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf2-cig2',
    ipaddr: '172.28.138.49',
    recvaet: 'CIGA_MCF_NON_EV',
    port: '7200',
    campus: 'MCF',
    sendaet1: 'ULTRA_ARCHIVE',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma1-cig1',
    ipaddr: '10.239.24.8',
    recvaet: 'CIGA_MCA_NON_EV',
    port: '7200',
    campus: 'MCA',
    sendaet1: 'ULTRA_ARCHIVE',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma1-cig2',
    ipaddr: '10.239.24.9',
    recvaet: 'CIGA_MCA_NON_EV',
    port: '7200',
    campus: 'MCA',
    sendaet1: 'ULTRA_ARCHIVE',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma2-cig1',
    ipaddr: '10.239.24.13',
    recvaet: 'CIGA_MCA_NON_EV',
    port: '7200',
    campus: 'MCA',
    sendaet1: 'ULTRA_ARCHIVE',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma2-cig2',
    ipaddr: '10.239.24.17',
    recvaet: 'CIGA_MCA_NON_EV',
    port: '7200',
    campus: 'MCA',
    sendaet1: 'ULTRA_ARCHIVE',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ei1-cig1',
    ipaddr: '10.128.233.101',
    recvaet: 'CIGA_MCR_RCV',
    port: '7900',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf1-cig1',
    ipaddr: '172.28.138.46',
    recvaet: 'CIGA_MCF_RCV',
    port: '7900',
    campus: 'MCF',
    sendaet1: 'MCFMIDPROD1',
    sendaet2: 'MCFMIDPROD1',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1fo1-cig1',
    ipaddr: '10.128.232.151',
    recvaet: 'CIGA_MCR_NON_PRE',
    port: '7110',
    campus: 'MCR',
    sendaet1: 'PRODDECO_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1fo1-cig2',
    ipaddr: '10.128.232.152',
    recvaet: 'CIGA_MCR_NON_PRE',
    port: '7110',
    campus: 'MCR',
    sendaet1: 'PRODDECO_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1fo1-cig1',
    ipaddr: '10.128.232.151',
    recvaet: 'CIGA_MCR_ORD_PRE',
    port: '6110',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1fo1-cig2',
    ipaddr: '10.128.232.152',
    recvaet: 'CIGA_MCR_ORD_PRE',
    port: '6110',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ei1-cig1',
    ipaddr: '10.128.233.101',
    recvaet: 'CIGA_MCR_NON_PRE',
    port: '7110',
    campus: 'MCR',
    sendaet1: 'PRODDECO_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ei1-cig2',
    ipaddr: '10.128.233.102',
    recvaet: 'CIGA_MCR_NON_PRE',
    port: '7110',
    campus: 'MCR',
    sendaet1: 'PRODDECO_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ei1-cig1',
    ipaddr: '10.128.233.101',
    recvaet: 'CIGA_MCR_ORD_PRE',
    port: '6110',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ei1-cig2',
    ipaddr: '10.128.233.102',
    recvaet: 'CIGA_MCR_ORD_PRE',
    port: '6110',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ei1-cig1',
    ipaddr: '10.128.200.17',
    recvaet: 'CIGA_MCR_ORD_PRE',
    port: '6110',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ei1-cig1',
    ipaddr: '10.128.200.17',
    recvaet: 'CIGA_MCR_NON_PRE',
    port: '7110',
    campus: 'MCR',
    sendaet1: 'PRODDECO_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ei1-cig2',
    ipaddr: '10.128.200.20',
    recvaet: 'CIGA_MCR_ORD_PRE',
    port: '6110',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ei1-cig2',
    ipaddr: '10.128.200.20',
    recvaet: 'CIGA_MCR_NON_PRE',
    port: '7110',
    campus: 'MCR',
    sendaet1: 'PRODDECO_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ha1-cig1',
    ipaddr: '10.128.200.8',
    recvaet: 'CIGA_MCR_ORD_PRE',
    port: '6110',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ha1-cig1',
    ipaddr: '10.128.200.8',
    recvaet: 'CIGA_MCR_NON_PRE',
    port: '7110',
    campus: 'MCR',
    sendaet1: 'PRODDECO_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ha1-cig2',
    ipaddr: '10.128.200.14',
    recvaet: 'CIGA_MCR_ORD_PRE',
    port: '6110',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ha1-cig2',
    ipaddr: '10.128.200.14',
    recvaet: 'CIGA_MCR_NON_PRE',
    port: '7110',
    campus: 'MCR',
    sendaet1: 'PRODDECO_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'R5029423',
    ipaddr: '172.24.109.205',
    recvaet: ' LQW_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'R5029423',
    ipaddr: '172.24.109.205',
    recvaet: ' LQW_MCR_NON',
    port: '7100',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ei1-cig1',
    ipaddr: '10.128.200.17',
    recvaet: 'CIGA_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'CLINICAL_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ei1-cig2',
    ipaddr: '10.128.200.20',
    recvaet: 'CIGA_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'CLINICAL_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ei1-cig1',
    ipaddr: '10.128.200.17',
    recvaet: 'CIGA_MCR_ORD_EV',
    port: '6200',
    campus: 'MCR',
    sendaet1: 'IAU_CLUSTER',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ei1-cig2',
    ipaddr: '10.128.200.20',
    recvaet: 'CIGA_MCR_ORD_EV',
    port: '6200',
    campus: 'MCR',
    sendaet1: 'IAU_CLUSTER',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ei1-cig1',
    ipaddr: '10.128.200.17',
    recvaet: 'CIGA_MCR_ORD_VIP',
    port: '6300',
    campus: 'MCR',
    sendaet1: '001SMRD140DRSP',
    sendaet2: 'W4X1',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ei1-cig1',
    ipaddr: '10.128.200.17',
    recvaet: 'CIGA_MCR_NON',
    port: '7100',
    campus: 'MCR',
    sendaet1: 'CLINICAL_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ei1-cig2',
    ipaddr: '10.128.200.20',
    recvaet: 'CIGA_MCR_NON',
    port: '7100',
    campus: 'MCR',
    sendaet1: 'CLINICAL_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ei1-cig1',
    ipaddr: '10.128.200.17',
    recvaet: 'CIGA_MCR_NON_EV',
    port: '7200',
    campus: 'MCR',
    sendaet1: 'ALI_SCU',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ei1-cig2',
    ipaddr: '10.128.200.20',
    recvaet: 'CIGA_MCR_NON_EV',
    port: '7200',
    campus: 'MCR',
    sendaet1: 'ALI_SCU',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ei1-cig1',
    ipaddr: '10.128.200.17',
    recvaet: 'CIGA_MCR_NON_VIP',
    port: '7300',
    campus: 'MCR',
    sendaet1: 'scimage-cluster',
    sendaet2: 'tstroke-cluster',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ha1-cig1',
    ipaddr: '10.128.200.8',
    recvaet: 'CIGA_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'CLINICAL_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ha1-cig2',
    ipaddr: '10.128.200.14',
    recvaet: 'CIGA_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'CLINICAL_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ha1-cig1',
    ipaddr: '10.128.200.8',
    recvaet: 'CIGA_MCR_ORD_EV',
    port: '6200',
    campus: 'MCR',
    sendaet1: 'IAU_CLUSTER',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ha1-cig2',
    ipaddr: '10.128.200.14',
    recvaet: 'CIGA_MCR_ORD_EV',
    port: '6200',
    campus: 'MCR',
    sendaet1: 'IAU_CLUSTER',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ha1-cig1',
    ipaddr: '10.128.200.8',
    recvaet: 'CIGA_MCR_ORD_VIP',
    port: '6300',
    campus: 'MCR',
    sendaet1: '001SMRD140DRSP',
    sendaet2: 'W4X1',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ha1-cig1',
    ipaddr: '10.128.200.8',
    recvaet: 'CIGA_MCR_NON',
    port: '7100',
    campus: 'MCR',
    sendaet1: 'CLINICAL_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ha1-cig2',
    ipaddr: '10.128.200.14',
    recvaet: 'CIGA_MCR_NON',
    port: '7100',
    campus: 'MCR',
    sendaet1: 'CLINICAL_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ha1-cig1',
    ipaddr: '10.128.200.8',
    recvaet: 'CIGA_MCR_NON_EV',
    port: '7200',
    campus: 'MCR',
    sendaet1: 'ALI_SCU',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ha1-cig2',
    ipaddr: '10.128.200.14',
    recvaet: 'CIGA_MCR_NON_EV',
    port: '7200',
    campus: 'MCR',
    sendaet1: 'ALI_SCU',
    sendaet2: 'ULTRA_ARCHIVE',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp2ha1-cig1',
    ipaddr: '10.128.200.8',
    recvaet: 'CIGA_MCR_NON_VIP',
    port: '7300',
    campus: 'MCR',
    sendaet1: 'scimage-cluster',
    sendaet2: 'tstroke-cluster',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma1-cig1',
    ipaddr: '10.239.24.8',
    recvaet: 'CIGA_MCA_NON_PRE',
    port: '7110',
    campus: 'MCA',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'ARZMIDIAPROD',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma1-cig1',
    ipaddr: '10.239.24.8',
    recvaet: 'CIGA_MCA_ORD_PRE',
    port: '6110',
    campus: 'MCA',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'ARZMIDIAPROD',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma1-cig2',
    ipaddr: '10.239.24.9',
    recvaet: 'CIGA_MCA_ORD_PRE',
    port: '6110',
    campus: 'MCA',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'ARZMIDIAPROD',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma2-cig1',
    ipaddr: '10.239.24.13',
    recvaet: 'CIGA_MCA_ORD_PRE',
    port: '6110',
    campus: 'MCA',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'ARZMIDIAPROD',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma2-cig2',
    ipaddr: '10.239.24.17',
    recvaet: 'CIGA_MCA_ORD_PRE',
    port: '6110',
    campus: 'MCA',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'ARZMIDIAPROD',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma1-cig2',
    ipaddr: '10.239.24.9',
    recvaet: 'CIGA_MCA_NON_PRE',
    port: '7110',
    campus: 'MCA',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'ARZMIDIAPROD',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma2-cig1',
    ipaddr: '10.239.24.13',
    recvaet: 'CIGA_MCA_NON_PRE',
    port: '7110',
    campus: 'MCA',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'ARZMIDIAPROD',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1ma2-cig2',
    ipaddr: '10.239.24.17',
    recvaet: 'CIGA_MCA_NON_PRE',
    port: '7110',
    campus: 'MCA',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'ARZMIDIAPROD',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf1-cig1',
    ipaddr: '172.28.138.46',
    recvaet: 'CIGA_MCF_ORD_PRE',
    port: '6110',
    campus: 'MCF',
    sendaet1: 'MCFMIDPROD1',
    sendaet2: 'MCFMIDPROD1',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf1-cig2',
    ipaddr: '172.28.138.47',
    recvaet: 'CIGA_MCF_ORD_PRE',
    port: '6110',
    campus: 'MCF',
    sendaet1: 'MCFMIDPROD1',
    sendaet2: 'MCFMIDPROD1',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf2-cig1',
    ipaddr: '172.28.138.48',
    recvaet: 'CIGA_MCF_ORD_PRE',
    port: '6110',
    campus: 'MCF',
    sendaet1: 'MCFMIDPROD1',
    sendaet2: 'MCFMIDPROD1',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf2-cig2',
    ipaddr: '172.28.138.49',
    recvaet: 'CIGA_MCF_ORD_PRE',
    port: '6110',
    campus: 'MCF',
    sendaet1: 'MCFMIDPROD1',
    sendaet2: 'MCFMIDPROD1',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf1-cig1',
    ipaddr: '172.28.138.46',
    recvaet: 'CIGA_MCF_NON_PRE',
    port: '7110',
    campus: 'MCF',
    sendaet1: 'MCFMIDPROD1',
    sendaet2: 'MCFMIDPROD1',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf1-cig2',
    ipaddr: '172.28.138.47',
    recvaet: 'CIGA_MCF_NON_PRE',
    port: '7110',
    campus: 'MCF',
    sendaet1: 'MCFMIDPROD1',
    sendaet2: 'MCFMIDPROD1',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf2-cig1',
    ipaddr: '172.28.138.48',
    recvaet: 'CIGA_MCF_NON_PRE',
    port: '7110',
    campus: 'MCF',
    sendaet1: 'MCFMIDPROD1',
    sendaet2: 'MCFMIDPROD1',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'iasp1mf2-cig2',
    ipaddr: '172.28.138.49',
    recvaet: 'CIGA_MCF_NON_PRE',
    port: '7110',
    campus: 'MCF',
    sendaet1: 'MCFMIDPROD1',
    sendaet2: 'MCFMIDPROD1',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'R5192965',
    ipaddr: '10.205.11.13',
    recvaet: 'SLK_MCR_ORD',
    port: '6200',
    campus: 'MCR',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'R5193050',
    ipaddr: '172.24.110.220',
    recvaet: 'SLK_MCR_ORD',
    port: '6200',
    campus: 'MCR',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'R5195656',
    ipaddr: '172.24.109.17',
    recvaet: 'BA_MCR_ORD',
    port: '6100',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'prod',
    aettype: 'receiver',
    hostname: 'R5195656',
    ipaddr: '172.24.109.17',
    recvaet: 'BA_MCR_NON',
    port: '7100',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1fo1-cig1',
    ipaddr: '10.128.232.151',
    recvaet: 'CIGA_MCR_NONSTG',
    port: '7109',
    campus: 'MCR',
    sendaet1: 'PRODDECO_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1fo1-cig2',
    ipaddr: '10.128.232.152',
    recvaet: 'CIGA_MCR_NONSTG',
    port: '7109',
    campus: 'MCR',
    sendaet1: 'PRODDECO_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1fo1-cig1',
    ipaddr: '10.128.232.151',
    recvaet: 'CIGA_MCR_ORDSTG',
    port: '6109',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1fo1-cig2',
    ipaddr: '10.128.232.152',
    recvaet: 'CIGA_MCR_ORDSTG',
    port: '6109',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1ei1-cig1',
    ipaddr: '10.128.233.101',
    recvaet: 'CIGA_MCR_NONSTG',
    port: '7109',
    campus: 'MCR',
    sendaet1: 'PRODDECO_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1ei1-cig2',
    ipaddr: '10.128.233.102',
    recvaet: 'CIGA_MCR_NONSTG',
    port: '7109',
    campus: 'MCR',
    sendaet1: 'PRODDECO_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1ei1-cig1',
    ipaddr: '10.128.233.101',
    recvaet: 'CIGA_MCR_ORDSTG',
    port: '6109',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1ei1-cig2',
    ipaddr: '10.128.233.102',
    recvaet: 'CIGA_MCR_ORDSTG',
    port: '6109',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp2ei1-cig1',
    ipaddr: '10.128.200.17',
    recvaet: 'CIGA_MCR_ORDSTG',
    port: '6109',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp2ei1-cig1',
    ipaddr: '10.128.200.17',
    recvaet: 'CIGA_MCR_NONSTG',
    port: '7109',
    campus: 'MCR',
    sendaet1: 'PRODDECO_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp2ei1-cig2',
    ipaddr: '10.128.200.20',
    recvaet: 'CIGA_MCR_ORDSTG',
    port: '6109',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp2ei1-cig2',
    ipaddr: '10.128.200.20',
    recvaet: 'CIGA_MCR_NONSTG',
    port: '7109',
    campus: 'MCR',
    sendaet1: 'PRODDECO_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp2ha1-cig1',
    ipaddr: '10.128.200.8',
    recvaet: 'CIGA_MCR_ORDSTG',
    port: '6109',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp2ha1-cig1',
    ipaddr: '10.128.200.8',
    recvaet: 'CIGA_MCR_NONSTG',
    port: '7109',
    campus: 'MCR',
    sendaet1: 'PRODDECO_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp2ha1-cig2',
    ipaddr: '10.128.200.14',
    recvaet: 'CIGA_MCR_ORDSTG',
    port: '6109',
    campus: 'MCR',
    sendaet1: 'TEAM_SCU',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp2ha1-cig2',
    ipaddr: '10.128.200.14',
    recvaet: 'CIGA_MCR_NONSTG',
    port: '7109',
    campus: 'MCR',
    sendaet1: 'PRODDECO_SCP',
    sendaet2: 'TEAM_SCU',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1ma1-cig1',
    ipaddr: '10.239.24.8',
    recvaet: 'CIGA_MCA_NONSTG',
    port: '7109',
    campus: 'MCA',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'ARZMIDIAPROD',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1ma1-cig1',
    ipaddr: '10.239.24.8',
    recvaet: 'CIGA_MCA_ORDSTG',
    port: '6109',
    campus: 'MCA',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'ARZMIDIAPROD',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'cigamca',
    ipaddr: '172.16.196.14',
    recvaet: 'CIGA_MCA_NONSTG',
    port: '7109',
    campus: 'MCA',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'ARZMIDIAPROD',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'cigamca',
    ipaddr: '172.16.196.14',
    recvaet: 'CIGA_MCA_ORDSTG',
    port: '6109',
    campus: 'MCA',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'ARZMIDIAPROD',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1ma1-cig2',
    ipaddr: '10.239.24.9',
    recvaet: 'CIGA_MCA_ORDSTG',
    port: '6109',
    campus: 'MCA',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'ARZMIDIAPROD',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1ma2-cig1',
    ipaddr: '10.239.24.13',
    recvaet: 'CIGA_MCA_ORDSTG',
    port: '6109',
    campus: 'MCA',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'ARZMIDIAPROD',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1ma2-cig2',
    ipaddr: '10.239.24.17',
    recvaet: 'CIGA_MCA_ORDSTG',
    port: '6109',
    campus: 'MCA',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'ARZMIDIAPROD',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1ma1-cig2',
    ipaddr: '10.239.24.9',
    recvaet: 'CIGA_MCA_NONSTG',
    port: '7109',
    campus: 'MCA',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'ARZMIDIAPROD',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1ma2-cig1',
    ipaddr: '10.239.24.13',
    recvaet: 'CIGA_MCA_NONSTG',
    port: '7109',
    campus: 'MCA',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'ARZMIDIAPROD',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1ma2-cig2',
    ipaddr: '10.239.24.17',
    recvaet: 'CIGA_MCA_NONSTG',
    port: '7109',
    campus: 'MCA',
    sendaet1: 'ARZMIDIAPROD',
    sendaet2: 'ARZMIDIAPROD',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1mf1-cig1',
    ipaddr: '172.28.138.46',
    recvaet: 'CIGA_MCF_ORDSTG',
    port: '6109',
    campus: 'MCF',
    sendaet1: 'MCFMIDPROD1',
    sendaet2: 'MCFMIDPROD1',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1mf1-cig2',
    ipaddr: '172.28.138.47',
    recvaet: 'CIGA_MCF_ORDSTG',
    port: '6109',
    campus: 'MCF',
    sendaet1: 'MCFMIDPROD1',
    sendaet2: 'MCFMIDPROD1',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1mf2-cig1',
    ipaddr: '172.28.138.48',
    recvaet: 'CIGA_MCF_ORDSTG',
    port: '6109',
    campus: 'MCF',
    sendaet1: 'MCFMIDPROD1',
    sendaet2: 'MCFMIDPROD1',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1mf2-cig2',
    ipaddr: '172.28.138.49',
    recvaet: 'CIGA_MCF_ORDSTG',
    port: '6109',
    campus: 'MCF',
    sendaet1: 'MCFMIDPROD1',
    sendaet2: 'MCFMIDPROD1',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1mf1-cig1',
    ipaddr: '172.28.138.46',
    recvaet: 'CIGA_MCF_NONSTG',
    port: '7109',
    campus: 'MCF',
    sendaet1: 'MCFMIDPROD1',
    sendaet2: 'MCFMIDPROD1',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1mf1-cig2',
    ipaddr: '172.28.138.47',
    recvaet: 'CIGA_MCF_NONSTG',
    port: '7109',
    campus: 'MCF',
    sendaet1: 'MCFMIDPROD1',
    sendaet2: 'MCFMIDPROD1',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1mf2-cig1',
    ipaddr: '172.28.138.48',
    recvaet: 'CIGA_MCF_NONSTG',
    port: '7109',
    campus: 'MCF',
    sendaet1: 'MCFMIDPROD1',
    sendaet2: 'MCFMIDPROD1',
  },
  {
    queue: 'preprod',
    aettype: 'receiver',
    hostname: 'iasp1mf2-cig2',
    ipaddr: '172.28.138.49',
    recvaet: 'CIGA_MCF_NONSTG',
    port: '7109',
    campus: 'MCF',
    sendaet1: 'MCFMIDPROD1',
    sendaet2: 'MCFMIDPROD1',
  },
];

// 129.176.169.21   cigaprod
// 172.29.5.31   cigamcf
// 172.16.196.14 cigamca
// 10.128.162.177 cigaint
